apiVersion: v1
kind: ConfigMap
metadata:
  name: auto-parking-config
  namespace: default
data:
  APP_ENV: "production"
  SERVICE_NAME: "auto-parking"
  DATABASE_URL: "postgresql://$DATABASE_USER:$DATABASE_PASSWORD@auto-parking-postgres-rw.auto-parking.svc.cluster.local:5432/auto-parking"
